[project]
name = "cifar10"
version = "0.1.0"
description = "CIFAR-10 backend experiment"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
  { name = "Aleksa Mihajlovic", email = "mihajlovic.aleksa@gmail.com" }
]


dependencies = [
  "numpy>=2.1.0",
  "pandas==2.2.2",
  "matplotlib==3.9.2",
  "fastapi>=0.116.1",
  "uvicorn>=0.35.0",
  "python-multipart>=0.0.20,<0.0.21",
  "tensorflow==2.19.0",
  "keras==3.10.0",
]

[project.optional-dependencies]
dev = [
  "jupyter>=1.1.1",
  "ipykernel>=7.0.1",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
